### ISSUE TITLE
Question on "so that it (hopefully) loads first" statement

### ISSUE THREAD

**Issue by gacarrillor** [opengisch/qpip#10]
The Readme states that _hopefully_ the plugin will be loaded first (see https://github.com/opengisch/qpip/blob/main/README.md?plain=1#L53).

Does it mean it needs to be loaded before all other plugins to behave properly or just before the plugins that depend on it?

If it's the latter, thankfully we can get rid of the "(hopefully)" part, because of https://github.com/qgis/QGIS/pull/44906

**Comment by m-kuhn** [comment]
The reason is that the python path needs to be adjusted before dependant plugins are loaded.

So that's good news, if I understand correctly, this will work already without any modifications (and it's only about improving the docs by removing the "hopefully" word)?

**Comment by gacarrillor** [comment]
> So that's good news, if I understand correctly, this will work already without any modifications (and it's only about improving the docs by removing the "hopefully" word)?

Right, without touching anything on any plugin, since v3.22, QGIS does the right thing loading dependent plugins only after all their (plugin) dependencies are loaded!

I just opened #11 to remove the `(hopefully)` word.
