### ISSUE TITLE
TypeError in combination with QFieldSync

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/qpip#19]
It worked great on one of my computers and failed on another:

This is the traceback:

```
pyplugin_installer.instance().onManagerClose()


Traceback (most recent call last):
  File "", line 1, in 
  File "C:\Users/axa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\a00_qpip\plugin.py", line 127, in patched_load_plugin
    dialog, run_gui = self.check_deps(additional_plugins=[packageName])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/axa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\a00_qpip\plugin.py", line 156, in check_deps
    if os.path.dirname(dist._path) != self.site_packages_path:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 277, in dirname
  File "", line 241, in split
TypeError: expected str, bytes or os.PathLike object, not Path
```

I diged a little bit deeper and added this line `log(f'dist: {dist._path}')` to which dist that failed: I don't get why it failed, but maybe through a try expect block around that check?

2024-09-25T08:01:17     INFO    dist: C:\Users\axa\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qfieldsync\libqfieldsync.whl/libqfieldsync-1.0.dist-info/

(the update seems to work nicely apart from this minor error!)

_Originally posted by @axelande in https://github.com/opengisch/qpip/issues/14#issuecomment-2373104359_

**Comment by m-kuhn** [comment]
I think this comes from here https://github.com/opengisch/qfieldsync/blob/master/qfieldsync/__init__.py#L31

@axelande I tried to reproduced with a small sample here but didn't manage

```
import pathlib
import os

p = pathlib.Path(__file__).parent.resolve() 
os.path.dirname(p)
```

is this code breaking at your place?

**Comment by axelande** [comment]
That is not the issue, the problem is with the `metadata`

When I run this in the qgis console:
```
from importlib import metadata
for dist in metadata.distributions():
    dist._path
```
It prints the path to all packages like this:
```
...
WindowsPath('C:/OSGeo4W/apps/Python312/Lib/site-packages/zipp-3.18.1.dist-info')
Path('C:\\Users\\axa\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\qfieldsync\\libqfieldsync.whl', 'libqfieldsync-1.0.dist-info/')
```
And it is this last line that does not work to run `os.path.dirname(dist._path)` on.

**Comment by borysiasty** [comment]
The same error here. The path to the `qfieldsync/libqfieldsync.whl/ibqfieldsync-1.0.dist-info` is type of `zipfile.Path`
and is not supported by `os.path.dirname()`. 

Can be wheels supported at all? If so, maybe just convert all the Path-like types into str?

```
156: -            if os.path.dirname(dist._path) != self.site_packages_path:
156: +            if os.path.dirname(str(dist._path)) != self.site_packages_path:
```

**Comment by m-kuhn** [comment]
> The same error here. The path to the `qfieldsync/libqfieldsync.whl/ibqfieldsync-1.0.dist-info` is type of `zipfile.Path` and is not supported by `os.path.dirname()`.
> 
> Can be wheels supported at all? If so, maybe just convert all the Path-like types into str?
> 
> ```
> 156: -            if os.path.dirname(dist._path) != self.site_packages_path:
> 156: +            if os.path.dirname(str(dist._path)) != self.site_packages_path:
> ```

Thanks for that !
That sounds good to me, would you open a PR for that?

**Comment by borysiasty** [comment]
Sure, a patch is on the way!
