### ISSUE TITLE
Error during installation of plugin in QGS 3.34 (LTS)

### ISSUE THREAD

**Issue by Kilian-Sosa** [opengisch/qpip#24]
Hi!

I have QGIS 3.34.11 (Python 3.12.6) and am getting the following error just after installing QPIP and trying to run my plugin on my machine and I cannot find a solution for it:

"An error occurred during execution of following code:
pyplugin_installer.instance().installFromZipFile(r'C:/Test/QGIS Test Monitoring/plugin_versions/Test Monitoring 7.5.zip')

Traceback (most recent call last):  File "", line 1, in   File "C:\PROGRA~1/QGIS33~1.11/apps/qgis-ltr/./python\pyplugin_installer\installer.py", line 673, in installFromZipFile    loadPlugin(pluginName)  File "C:\Users/matjaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\a00_qpip\plugin.py", line 127, in patched_load_plugin    dialog, run_gui = self.check_deps(additional_plugins=[packageName])                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users/matjaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\a00_qpip\plugin.py", line 156, in check_deps    if os.path.dirname(dist._path) != self.site_packages_path:       ^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "", line 277, in dirname  File "", line 241, in splitTypeError: expected str, bytes or os.PathLike object, not Path
Python version:
3.12.6 (main, Sep  7 2024, 18:59:42) [MSC v.1938 64 bit (AMD64)]
QGIS version:
3.34.11-Prizren 'Prizren', 2904bcec
Python path:
['C:\\Users\\matjaz\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\dependencies', 'C:/PROGRA~1/QGIS33~1.11/apps/qgis-ltr/./python', 'C:/Users/matjaz/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python', 'C:/Users/matjaz/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins', 'C:/PROGRA~1/QGIS33~1.11/apps/qgis-ltr/./python/plugins', 'C:\\PROGRA~1\\QGIS33~1.11\\apps\\grass\\grass84\\etc\\python', 'C:\\Users\\matjaz\\Documents', 'C:\\Program Files\\QGIS 3.34.11\\bin\\python312.zip', 'C:\\PROGRA~1\\QGIS33~1.11\\apps\\Python312\\DLLs', 'C:\\PROGRA~1\\QGIS33~1.11\\apps\\Python312\\Lib', 'C:\\Program Files\\QGIS 3.34.11\\bin', 'C:\\PROGRA~1\\QGIS33~1.11\\apps\\Python312', 'C:\\PROGRA~1\\QGIS33~1.11\\apps\\Python312\\Lib\\site-packages', 'C:\\PROGRA~1\\QGIS33~1.11\\apps\\Python312\\Lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGIS33~1.11\\apps\\Python312\\Lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGIS33~1.11\\apps\\Python312\\Lib\\site-packages\\Pythonwin', 'C:/Users/matjaz/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python', 'C:\\Users\\matjaz\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\SentinelHub\\external\\oauthlib-3.2.2-py3-none-any.whl', 'C:\\Users\\matjaz\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\SentinelHub\\external\\requests_oauthlib-1.3.1-py2.py3-none-any.whl']"

Thank you in advance for your help and If you need anymore information, please let me know!

**Comment by borysiasty** [comment]
This bug was fixed this morning, so please wait for the release (or download from here  :) 
The current version conflicts with the `SentinelHub` plugin (and some others).

**Comment by Kilian-Sosa** [comment]
Apologies @borysiasty, I did not see it. Any idea when the new version will be released?

**Comment by borysiasty** [comment]
I hope soon :) @m-kuhn might say more.

**Comment by borysiasty** [comment]
Just released
