### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'python' 

### ISSUE THREAD

**Issue by angusmcb** [opengisch/qpip#5]
Hello, I am very happy to have found this plugin which seems to solve a very common problem for qgis plugins!

However, after clicking 'ok' from the dependancy manager UI, with plugins selected to install, I am getting the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'python' 
Traceback (most recent call last):
  File "/home/me/.local/share/QGIS/QGIS3/profiles/default/python/plugins/a00_qpip/plugin.py", line 252, in check
    self.check_deps_and_prompt_install(force_gui=True)
  File "/home/me/.local/share/QGIS/QGIS3/profiles/default/python/plugins/a00_qpip/plugin.py", line 182, in check_deps_and_prompt_install
    self.pip_install_reqs(reqs_to_install)
  File "/home/me/.local/share/QGIS/QGIS3/profiles/default/python/plugins/a00_qpip/plugin.py", line 238, in pip_install_reqs
    run_cmd(
  File "/home/me/.local/share/QGIS/QGIS3/profiles/default/python/plugins/a00_qpip/utils.py", line 65, in run_cmd
    process = Popen(args, stdout=PIPE, stderr=STDOUT, startupinfo=startupinfo)
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'


Python version: 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0] 
QGIS version: 3.38.1-Grenoble Grenoble, 3d4177afc6b 

```

**Comment by angusmcb** [comment]
After further investigation, I think this is because on Ubuntu it's python3, not python.

This could help:
https://stackoverflow.com/questions/2589711/find-full-path-of-the-python-interpreter-python-executable

**Comment by angusmcb** [comment]
I've relalised that my fix doesn't necessarily work on windows.

sys.executable points to 'C:\\OSGeo4W\\bin\\qgis-bin.exe'

I can't see what the reliable solution is.

**Comment by m-kuhn** [comment]
I could see two approaches:

1. a. rely on a specific packaging layout on windows (e.g. assume `python3.exe` living in the same path as `sys.executable`) or
b. search for the python executable in `PATH`
2. a. Use a tool like`pip-api` or
b. `pip-shims`

A bit of experiments will be required in a python console on a windows QGIS installation. And a bit of investigation if one of these packages comes pre-installed.

**Comment by angusmcb** [comment]
There is a long open bug about sys.executable here:

https://github.com/qgis/QGIS/issues/45646

**Comment by m-kuhn** [comment]
> There is a long open bug about sys.executable here:
> 
> [qgis/QGIS#45646](https://github.com/qgis/QGIS/issues/45646)

I can see why we'd want to get some python executable, at the same time, it seems reasonable that if python is interpreted through the qgis executable, it's impossible to determine a python executable that happens to link to the same libpython.

We probably have to be pragmatic and find a way that works good enough in common cases.

**Comment by angusmcb** [comment]
I've made a pull request for what I think is the simplest fix.
