### ISSUE TITLE
USERPROFILE/python/dependencies/Lib/site-packages    not path on linux

### ISSUE THREAD

**Issue by angusmcb** [opengisch/qpip#8]
qpip adds the following to python path:
`USERPROFILE/python/dependencies/Lib/site-packages`

However, this is only the location where packages will be installed on windows. The location on other systems seems to be... complicated!

Possible fix is to switch from using pip with '--prefix' to '--target', but I do not understand the full implications of doing this.

In particular, what would happen to this path?  `USERPROFILE/python/dependencies/Scripts`

**Comment by m-kuhn** [comment]
> qpip adds the following to python path: `USERPROFILE/python/dependencies/Lib/site-packages`
> 
> However, this is only the location where packages will be installed on windows. The location on other systems seems to be... complicated!
> 
> Possible fix is to switch from using pip with '--prefix' to '--target', but I do not understand the full implications of doing this.
> 
> In particular, what would happen to this path? `USERPROFILE/python/dependencies/Scripts`

It becomes `USERPROFILE/python/dependencies/bin`. According to my tests on linux and windows.

Ideally, we would be able to query the system for these paths, but I am not aware of a way for that.
Or we could possibly work with a virtualenv (see https://stackoverflow.com/questions/6943208/activate-a-virtualenv-with-a-python-script for how to activate one in a running interpreter), but that would need some more testing.

As a quick fix, I am in favor of `--target`.

**Comment by m-kuhn** [comment]
Implemented in https://github.com/opengisch/qpip/commit/b45bf5a2b087fafd1db55903d82c820ac4e6876b
